# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b90d35041d1c90fb25688f843d78d6b0ffbb79a87933963bd7778cae7cf7a0dd9b9800f9ab08eb43c20cb2ffe755817414bb939f9ffd4074f62331ee90ab1220

test:
  secret_key_base: 5255089bc1ac9b667477332339451c16cbc96d8b5aefe34c1654b5f61d8983591a399ad30fe31c433f06046d14b2abc5b39b30fde2d4b454cf7acef8fa83e1c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
